const data = {
  products: [
    {
      name: "Nike Slim Tshirt",
      slug: "Nike-Slim-Tshirt",
      category: "Shirts",
      image: "images/nike slim tshirt.webp",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numREviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Addidas Slim Tshirt",
      slug: "addidas-Slim-Tshirt",
      category: "Shirts",
      image: "/images/addidas tshirt.webp",
      price: 250,
      countInStock: 20,
      brand: "Addida",
      rating: 5,
      numREviews: 15,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-Slim-pant",
      category: "pants",
      image: "/images/nike pant.webp",
      price: 550,
      countInStock: 50,
      brand: "Nike",
      rating: 4.9,
      numREviews: 15,
      description: "high quality pant",
    },
    {
      name: "Addidas Slim Pant",
      slug: "addidas-Slim-pant",
      category: "pants",
      image: "/images/nike slim tshirt.webp",
      price: 558,
      countInStock: 50,
      brand: "Addidas",
      rating: 4.9,
      numREviews: 15,
      description: "high quality pant",
    },
  ],
};
export default data
